export const initialEmployees = [
  { id: 'emp-1', name: 'Angelica', color: '#EB4213', skills: {} },
  { id: 'emp-2', name: 'Tetiana', color: '#FF99DC', skills: {} },
  { id: 'emp-3', name: 'An', color: '#826DEE', skills: {} },
  { id: 'emp-4', name: 'Gaudiosa', color: '#D8F382', skills: {} },
  { id: 'emp-5', name: 'Khemika', color: '#00C2A8', skills: {} },
  { id: 'emp-6', name: 'Cecilia', color: '#FFB000', skills: {} },
  { id: 'emp-7', name: 'Mellisa', color: '#3A86FF', skills: {} },
];

export const taskTemplates = [
  {
    id: 'task-opening-duties',
    groupId: 'sanitation',
    name: 'Opening Duties',
    colorVar: '--sanitation',
    baseMinutes: 30,
    variableMinutesPerCycle: 0,
    unitsPerCycle: 1,
    unitName: 'duties',
    isBatchProcess: false,
  },
  {
    id: 'task-closing-duties',
    groupId: 'sanitation',
    name: 'Closing Duties',
    colorVar: '--sanitation',
    baseMinutes: 45,
    variableMinutesPerCycle: 0,
    unitsPerCycle: 1,
    unitName: 'duties',
    isBatchProcess: false,
  },
  {
    id: 'task-misc-work',
    groupId: 'misc-work',
    name: 'Misc Work',
    colorVar: '--misc',
    baseMinutes: 30,
    variableMinutesPerCycle: 0,
    unitsPerCycle: 1,
    unitName: 'blocks',
    isBatchProcess: false,
  },
  {
    id: 'task-mixing-room-setup',
    groupId: 'dip-mixing',
    name: 'Mixing Room Set-up',
    colorVar: '--dip',
    baseMinutes: 30,
    variableMinutesPerCycle: 0,
    unitsPerCycle: 1,
    unitName: 'set-ups',
    isBatchProcess: false,
  },
  {
    id: 'task-mixing-cleanup',
    groupId: 'dip-mixing',
    name: 'Mixing Cleanup',
    colorVar: '--dip',
    baseMinutes: 60,
    variableMinutesPerCycle: 0,
    unitsPerCycle: 1,
    unitName: 'cleanups',
    isBatchProcess: false,
  },
  {
    id: 'task-sanitation',
    groupId: 'ferment-prep',
    name: 'Bucket Sanitation & Labels',
    colorVar: '--ferment',
    baseMinutes: 0,
    variableMinutesPerCycle: 45,
    unitsPerCycle: 50,
    unitName: 'buckets',
    isBatchProcess: false, // continuous scaling
  },
  {
    id: 'task-stickering',
    groupId: 'ferment-prep',
    name: 'Bacteria / Holdbac',
    colorVar: '--ferment',
    baseMinutes: 30,
    variableMinutesPerCycle: 0,
    unitsPerCycle: 1,
    unitName: 'buckets',
    isBatchProcess: false,
  },
  {
    id: 'task-boiling',
    groupId: 'ferment-prep',
    name: 'Boiling & Mixing Flow',
    colorVar: '--ferment',
    baseMinutes: 0,
    variableMinutesPerCycle: 3.43,
    unitsPerCycle: 1,
    unitName: 'buckets',
    isBatchProcess: false,
    assignmentRoles: ['Boiling Lead', 'Boiling Support'],
  },
  {
    id: 'task-mixing',
    groupId: 'ferment-prep',
    name: 'Fermentation Mixing',
    colorVar: '--ferment',
    baseMinutes: 0,
    variableMinutesPerCycle: 8,
    unitsPerCycle: 1.75,
    unitName: 'buckets',
    isBatchProcess: true,
  },
  {
    id: 'task-cleanup',
    groupId: 'ferment-prep',
    name: 'Fermentation Cleanup',
    colorVar: '--ferment',
    baseMinutes: 60,
    variableMinutesPerCycle: 0,
    unitsPerCycle: 1,
    unitName: 'buckets',
    isBatchProcess: false,
    assignmentRoles: ['Cleanup 1', 'Cleanup 2'],
  },
  {
    id: 'task-dip-mixing',
    groupId: 'dip-mixing',
    name: 'Dip Mixing',
    colorVar: '--dip',
    baseMinutes: 0,
    variableMinutesPerCycle: 7.8,
    unitsPerCycle: 1,
    unitName: 'batches',
    isBatchProcess: false,
    timingNote: 'Skilled capacity is up to 50 batches per day including room set-up and cleanup. Chive can mix in about 1 minute; spinach takes longer.',
  },
  {
    id: 'task-veg-beet',
    groupId: 'veg-prep',
    name: 'Beet Roast & Portion',
    colorVar: '--veg',
    baseMinutes: 165,
    variableMinutesPerCycle: 40,
    unitsPerCycle: 1,
    unitName: 'bags',
    isBatchProcess: false,
    maxPeopleAffectingDuration: 2,
  },
  {
    id: 'task-veg-cilantro',
    groupId: 'veg-prep',
    name: 'Cilantro Wash Prep',
    colorVar: '--veg',
    baseMinutes: 80,
    variableMinutesPerCycle: 160,
    variableMinutesPerCycleByWorkerCount: {
      2: 40,
    },
    unitsPerCycle: 12,
    unitName: 'boxes',
    isBatchProcess: false,
    maxPeopleAffectingDuration: 2,
  },
  {
    id: 'task-veg-jalapeno',
    groupId: 'veg-prep',
    name: 'Jalapeno Prep',
    colorVar: '--veg',
    baseMinutes: 0,
    variableMinutesPerCycle: 60,
    unitsPerCycle: 1,
    unitName: 'batches',
    isBatchProcess: true,
  },
  {
    id: 'task-veg-cucumber',
    groupId: 'veg-prep',
    name: 'Cucumber Prep',
    colorVar: '--veg',
    baseMinutes: 0,
    variableMinutesPerCycle: 140,
    unitsPerCycle: 12,
    unitName: 'cases',
    isBatchProcess: true,
  },
  {
    id: 'task-veg-smoking-nuts',
    groupId: 'veg-prep',
    name: 'Smoke Boiled Cashews',
    colorVar: '--veg',
    baseMinutes: 0,
    variableMinutesPerCycle: 100,
    unitsPerCycle: 4,
    unitName: 'buckets',
    isBatchProcess: true,
  },
  {
    id: 'task-veg-roasting-nuts',
    groupId: 'veg-prep',
    name: 'Roast Cashews',
    colorVar: '--veg',
    baseMinutes: 0,
    variableMinutesPerCycle: 15,
    unitsPerCycle: 1,
    unitName: 'runs',
    isBatchProcess: true,
  },
  {
    id: 'task-dry-mix',
    groupId: 'packaging-prep',
    name: 'Dry Mix Bags',
    colorVar: '--packaging',
    baseMinutes: 0,
    variableMinutesPerCycle: 1.33,
    unitsPerCycle: 1,
    unitName: 'bags',
    isBatchProcess: false,
    maxPeopleAffectingDuration: 99,
  },
  {
    id: 'task-date-containers',
    groupId: 'packaging-prep',
    name: 'Date Containers',
    colorVar: '--packaging',
    baseMinutes: 0,
    variableMinutesPerCycle: 35,
    unitsPerCycle: 1,
    unitName: 'boxes',
    isBatchProcess: true,
    maxPeopleAffectingDuration: 99,
  },
  {
    id: 'task-sticker-lids',
    groupId: 'packaging-prep',
    name: 'Sticker Lids',
    colorVar: '--packaging',
    baseMinutes: 0,
    variableMinutesPerCycle: 75,
    unitsPerCycle: 1,
    unitName: 'boxes',
    isBatchProcess: true,
    maxPeopleAffectingDuration: 99,
  },
  {
    id: 'task-tape-boxes',
    groupId: 'packaging-prep',
    name: 'Tape Cases/Boxes',
    colorVar: '--packaging',
    baseMinutes: 0,
    variableMinutesPerCycle: 60,
    unitsPerCycle: 300,
    unitName: 'cases',
    isBatchProcess: true,
    maxPeopleAffectingDuration: 99,
  },
  {
    id: 'task-dry-mix-prep-set',
    groupId: 'packaging-prep',
    name: 'Dry Mix Bags',
    colorVar: '--packaging',
    baseMinutes: 0,
    variableMinutesPerCycle: 67,
    unitsPerCycle: 1,
    unitName: 'prep sets',
    isBatchProcess: false,
    maxPeopleAffectingDuration: 99,
  },
  {
    id: 'task-dip-filling',
    groupId: 'dip-processing',
    name: 'Filling',
    colorVar: '--dip-process',
    baseMinutes: 0,
    variableMinutesPerCycle: 8.6,
    unitsPerCycle: 1,
    unitName: 'buckets',
    isBatchProcess: false,
  },
  {
    id: 'task-cheese-mixing',
    groupId: 'dip-mixing',
    name: 'Cheese Mixing',
    colorVar: '--dip',
    baseMinutes: 0,
    variableMinutesPerCycle: 10.26,
    unitsPerCycle: 1,
    unitName: 'batches',
    isBatchProcess: false,
    skillBasedDailyCapacity: {
      untrained: 28,
      beginner: 38,
      expert: 52,
      unassigned: 38,
    },
  },
  {
    id: 'task-cheese-moulds',
    groupId: 'cheese-processing',
    name: 'Cheese Moulds',
    colorVar: '--cheese',
    baseMinutes: 0,
    variableMinutesPerCycle: 60,
    unitsPerCycle: 42,
    unitName: 'pans',
    isBatchProcess: false,
  },
  {
    id: 'task-sauce-mixing',
    groupId: 'dip-mixing',
    name: 'Sauce Mixing',
    colorVar: '--dip',
    baseMinutes: 0,
    variableMinutesPerCycle: 7.8,
    unitsPerCycle: 1,
    unitName: 'batches',
    isBatchProcess: false,
    timingNote: 'Uses dip mixing timing with no changeover time.',
  },
  {
    id: 'task-sauce-filling',
    groupId: 'dip-processing',
    name: 'Sauce Filling',
    colorVar: '--dip-process',
    baseMinutes: 0,
    variableMinutesPerCycle: 7.5,
    unitsPerCycle: 1,
    unitName: 'buckets',
    isBatchProcess: false,
    timingNote: 'Capacity: 60 buckets per day.',
  },
  {
    id: 'task-mixing-support',
    groupId: 'misc-work',
    name: 'Mixing Support',
    colorVar: '--misc',
    baseMinutes: 90,
    variableMinutesPerCycle: 0,
    unitsPerCycle: 1,
    unitName: 'support blocks',
    isBatchProcess: false,
    timingNote: 'Measure oils, portion miso, and gather ingredients. Schedule in 1–2 hour blocks.',
  },
  {
    id: 'task-filling-floater',
    groupId: 'dip-processing',
    name: 'Filling Floater',
    colorVar: '--dip-process',
    baseMinutes: 570,
    variableMinutesPerCycle: 0,
    unitsPerCycle: 1,
    unitName: 'days',
    isBatchProcess: false,
    timingNote: 'All-day support: wash dishes and buckets, stock boxes, add sleeves during backups, and sticker cases.',
  },
  {
    id: 'task-packing-pallets',
    groupId: 'packaging-prep',
    name: 'Packing Pallets',
    colorVar: '--packaging',
    baseMinutes: 0,
    variableMinutesPerCycle: 60,
    unitsPerCycle: 1,
    unitName: 'pallets',
    isBatchProcess: false,
    maxPeopleAffectingDuration: 99,
    timingNote: '1 pallet (about 290 cases) per hour.',
  },
  {
    id: 'task-inventory-reconciling',
    groupId: 'misc-work',
    name: 'Inventory Reconciling',
    colorVar: '--misc',
    baseMinutes: 60,
    variableMinutesPerCycle: 0,
    unitsPerCycle: 1,
    unitName: 'counts',
    isBatchProcess: false,
    timingNote: 'Refresh inventory ID cards, count inventory, and update the ID cards.',
  },
  {
    id: 'task-cheese-slicing',
    groupId: 'cheese-processing',
    name: 'Cheese Slicing',
    colorVar: '--cheese',
    baseMinutes: 0,
    variableMinutesPerCycle: 30,
    variableMinutesPerCycleByWorkerCount: {
      2: 20,
      3: 20,
    },
    unitsPerCycle: 1,
    unitName: 'batches',
    isBatchProcess: false,
    maxPeopleAffectingDuration: 3,
  },
  {
    id: 'task-cheese-dipping',
    groupId: 'cheese-processing',
    name: 'Cheese Dipping',
    colorVar: '--cheese',
    baseMinutes: 0,
    variableMinutesPerCycle: 30,
    unitsPerCycle: 1,
    unitName: 'racks',
    isBatchProcess: false,
    maxPeopleAffectingDuration: 2,
  },
  {
    id: 'task-cheese-sealing',
    groupId: 'cheese-processing',
    name: 'Cheese Sealing',
    colorVar: '--cheese',
    baseMinutes: 0,
    variableMinutesPerCycle: 40,
    variableMinutesPerCycleByWorkerCount: {
      2: 20,
    },
    unitsPerCycle: 1,
    unitName: 'racks',
    isBatchProcess: false,
    maxPeopleAffectingDuration: 2,
    assignmentRoles: ['Loading Team', 'Receiving Team'],
  },
  {
    id: 'task-cheese-packing',
    groupId: 'cheese-processing',
    name: 'Cheese Packing',
    colorVar: '--cheese',
    baseMinutes: 0,
    variableMinutesPerCycle: 55,
    variableMinutesPerCycleByWorkerCount: {
      2: 27.5,
      3: 18.33,
    },
    unitsPerCycle: 1,
    unitName: 'batches',
    isBatchProcess: false,
    maxPeopleAffectingDuration: 3,
    assignmentRoles: ['Sealer 1', 'Sealer 2', 'Boxer'],
  },
  {
    id: 'task-qa-swab',
    groupId: 'sanitation',
    name: 'QA Swab Inspection',
    colorVar: '--sanitation',
    baseMinutes: 35,
    variableMinutesPerCycle: 0,
    unitsPerCycle: 1,
    unitName: 'inspections',
    isBatchProcess: false,
  },
  {
    id: 'task-dishes',
    groupId: 'sanitation',
    name: 'Dishes & Washdown',
    colorVar: '--sanitation',
    baseMinutes: 65,
    variableMinutesPerCycle: 0,
    unitsPerCycle: 1,
    unitName: 'blocks',
    isBatchProcess: false,
  },
  {
    id: 'task-garbage-recycling',
    groupId: 'sanitation',
    name: 'Garbage & Recycling',
    colorVar: '--sanitation',
    baseMinutes: 25,
    variableMinutesPerCycle: 0,
    unitsPerCycle: 1,
    unitName: 'blocks',
    isBatchProcess: false,
  },
];

export const runTemplates = [
  {
    id: 'run-fermentation',
    name: 'Fermentation Run',
    groupId: 'ferment-prep',
    inputType: 'single',
    inputUnit: 'buckets',
    bucketsPerInputUnit: 1,
    tasks: [
      'task-sanitation',
      'task-stickering',
      'task-boiling',
      'task-cleanup'
    ]
  },
  {
    id: 'run-dip-mixing',
    name: 'Mixing',
    groupId: 'dip-mixing',
    inputType: 'single',
    inputUnit: 'batches',
    bucketsPerInputUnit: 1,
    tasks: [
      'task-cheese-mixing',
      'task-dip-mixing',
      'task-sauce-mixing',
    ]
  },
  {
    id: 'run-veg-prep',
    name: 'Veggie Prep Run',
    groupId: 'veg-prep',
    inputType: 'single',
    inputUnit: 'runs',
    bucketsPerInputUnit: 1,
    tasks: [
      'task-veg-beet',
      'task-veg-cilantro',
      'task-veg-jalapeno',
      'task-veg-cucumber',
      'task-veg-smoking-nuts',
      'task-veg-roasting-nuts',
    ]
  },
  {
    id: 'run-packaging-prep',
    name: 'Packaging Prep Run',
    groupId: 'packaging-prep',
    inputType: 'single',
    inputUnit: 'prep sets',
    bucketsPerInputUnit: 1,
    tasks: [
      'task-date-containers',
      'task-sticker-lids',
      'task-tape-boxes',
      'task-dry-mix-prep-set',
      'task-packing-pallets',
    ]
  },
  {
    id: 'run-dip-processing',
    name: 'Dip Filling Run',
    groupId: 'dip-processing',
    inputType: 'single',
    inputUnit: 'buckets',
    bucketsPerInputUnit: 1,
    tasks: [
      'task-dip-filling',
      'task-sauce-filling',
    ]
  },
  {
    id: 'run-cheese-processing',
    name: 'Cheese Processing Run',
    groupId: 'cheese-processing',
    inputType: 'single',
    inputUnit: 'batches',
    bucketsPerInputUnit: 1,
    tasks: [
      'task-cheese-moulds',
      'task-cheese-slicing',
      'task-cheese-dipping',
      'task-cheese-sealing',
      'task-cheese-packing',
    ]
  },
  {
    id: 'run-support',
    name: 'Support Blocks',
    groupId: 'misc-work',
    inputType: 'single',
    inputUnit: 'blocks',
    bucketsPerInputUnit: 1,
    tasks: [
      'task-mixing-support',
      'task-filling-floater',
      'task-inventory-reconciling',
    ]
  },
  {
    id: 'run-sanitation-qa',
    name: 'Sanitation & QA Run',
    groupId: 'sanitation',
    inputType: 'single',
    inputUnit: 'blocks',
    bucketsPerInputUnit: 1,
    tasks: [
      'task-qa-swab',
      'task-dishes',
      'task-garbage-recycling',
    ]
  }
];

export const daysOfWeek = [
  { id: 'mon', name: 'Monday' },
  { id: 'tue', name: 'Tuesday' },
  { id: 'wed', name: 'Wednesday' },
  { id: 'thu', name: 'Thursday' },
  { id: 'fri', name: 'Friday' }
];

// Hours from 7 AM to 5 PM
export const hoursOfDay = Array.from({ length: 11 }, (_, i) => i + 7);
