export const initialEmployees = [
  { id: 'emp-1', name: 'Alice', skills: { 'task-sanitation': 'expert', 'task-boiling': 'beginner', 'task-cleanup': 'expert' } },
  { id: 'emp-2', name: 'Bob', skills: { 'task-sanitation': 'beginner', 'task-boiling': 'expert', 'task-cleanup': 'expert' } },
  { id: 'emp-3', name: 'Charlie', skills: { 'task-sanitation': 'untrained', 'task-boiling': 'untrained', 'task-cleanup': 'beginner' } },
];

export const taskTemplates = [
  {
    id: 'task-sanitation',
    groupId: 'ferment-prep',
    name: 'Bucket Sanitation',
    colorVar: '--ferment',
    baseMinutes: 0,
    variableMinutesPerCycle: 45,
    unitsPerCycle: 50,
    unitName: 'buckets',
    isBatchProcess: false, // continuous scaling
  },
  {
    id: 'task-stickering',
    groupId: 'ferment-prep',
    name: 'Stickering & Holdbac',
    colorVar: '--ferment',
    baseMinutes: 15,
    variableMinutesPerCycle: 0,
    unitsPerCycle: 1,
    unitName: 'buckets',
    isBatchProcess: false,
  },
  {
    id: 'task-boiling',
    groupId: 'ferment-prep',
    name: 'Fermentation Boiling',
    colorVar: '--ferment',
    baseMinutes: 0,
    variableMinutesPerCycle: 8,
    unitsPerCycle: 3,
    unitName: 'buckets',
    isBatchProcess: true, // Must run full cycles
  },
  {
    id: 'task-mixing',
    groupId: 'ferment-prep',
    name: 'Fermentation Mixing',
    colorVar: '--ferment',
    baseMinutes: 0,
    variableMinutesPerCycle: 8,
    unitsPerCycle: 1.75,
    unitName: 'buckets',
    isBatchProcess: true,
  },
  {
    id: 'task-cleanup',
    groupId: 'ferment-prep',
    name: 'Fermentation Cleanup',
    colorVar: '--ferment',
    baseMinutes: 120,
    variableMinutesPerCycle: 0,
    unitsPerCycle: 1,
    unitName: 'buckets',
    isBatchProcess: false,
  },
  {
    id: 'task-dip-mixing',
    groupId: 'dip-mixing',
    name: 'Dip Mixing',
    colorVar: '--dip',
    baseMinutes: 0,
    variableMinutesPerCycle: 8,
    unitsPerCycle: 1,
    unitName: 'batches',
    isBatchProcess: false,
  },
  {
    id: 'task-veg-beet',
    groupId: 'veg-prep',
    name: 'Beet Roast & Portion',
    colorVar: '--veg',
    baseMinutes: 165,
    variableMinutesPerCycle: 40,
    unitsPerCycle: 1,
    unitName: 'bags',
    isBatchProcess: false,
    maxPeopleAffectingDuration: 2,
  },
  {
    id: 'task-veg-cilantro',
    groupId: 'veg-prep',
    name: 'Cilantro Wash Prep',
    colorVar: '--veg',
    baseMinutes: 80,
    variableMinutesPerCycle: 160,
    variableMinutesPerCycleByWorkerCount: {
      2: 40,
    },
    unitsPerCycle: 12,
    unitName: 'boxes',
    isBatchProcess: false,
    maxPeopleAffectingDuration: 2,
  },
  {
    id: 'task-veg-jalapeno',
    groupId: 'veg-prep',
    name: 'Jalapeno Prep',
    colorVar: '--veg',
    baseMinutes: 0,
    variableMinutesPerCycle: 60,
    unitsPerCycle: 1,
    unitName: 'batches',
    isBatchProcess: true,
  },
  {
    id: 'task-veg-cucumber',
    groupId: 'veg-prep',
    name: 'Cucumber Prep',
    colorVar: '--veg',
    baseMinutes: 0,
    variableMinutesPerCycle: 140,
    unitsPerCycle: 12,
    unitName: 'cases',
    isBatchProcess: true,
  },
  {
    id: 'task-veg-smoking-nuts',
    groupId: 'veg-prep',
    name: 'Smoke Boiled Cashews',
    colorVar: '--veg',
    baseMinutes: 0,
    variableMinutesPerCycle: 100,
    unitsPerCycle: 4,
    unitName: 'buckets',
    isBatchProcess: true,
  },
  {
    id: 'task-veg-roasting-nuts',
    groupId: 'veg-prep',
    name: 'Roast Cashews',
    colorVar: '--veg',
    baseMinutes: 0,
    variableMinutesPerCycle: 15,
    unitsPerCycle: 1,
    unitName: 'runs',
    isBatchProcess: true,
  },
  {
    id: 'task-dry-mix',
    groupId: 'packaging-prep',
    name: 'Dry Mix Bags',
    colorVar: '--packaging',
    baseMinutes: 0,
    variableMinutesPerCycle: 1.33,
    unitsPerCycle: 1,
    unitName: 'bags',
    isBatchProcess: false,
  },
  {
    id: 'task-date-containers',
    groupId: 'packaging-prep',
    name: 'Date Containers',
    colorVar: '--packaging',
    baseMinutes: 0,
    variableMinutesPerCycle: 35,
    unitsPerCycle: 1,
    unitName: 'boxes',
    isBatchProcess: true,
  },
  {
    id: 'task-sticker-lids',
    groupId: 'packaging-prep',
    name: 'Sticker Lids',
    colorVar: '--packaging',
    baseMinutes: 0,
    variableMinutesPerCycle: 75,
    unitsPerCycle: 1,
    unitName: 'boxes',
    isBatchProcess: true,
  },
  {
    id: 'task-tape-boxes',
    groupId: 'packaging-prep',
    name: 'Tape Dip/Cheese Boxes',
    colorVar: '--packaging',
    baseMinutes: 0,
    variableMinutesPerCycle: 60,
    unitsPerCycle: 300,
    unitName: 'boxes',
    isBatchProcess: true,
  },
  {
    id: 'task-dry-mix-prep-set',
    groupId: 'packaging-prep',
    name: 'Dry Mix Bags',
    colorVar: '--packaging',
    baseMinutes: 0,
    variableMinutesPerCycle: 67,
    unitsPerCycle: 1,
    unitName: 'prep sets',
    isBatchProcess: false,
  },
  {
    id: 'task-dip-filling',
    groupId: 'dip-processing',
    name: 'Dip Filler Cycle',
    colorVar: '--dip-process',
    baseMinutes: 0,
    variableMinutesPerCycle: 8.6,
    unitsPerCycle: 1,
    unitName: 'buckets',
    isBatchProcess: false,
  },
  {
    id: 'task-dip-sealing',
    groupId: 'dip-processing',
    name: 'Dip Sealer Cycle',
    colorVar: '--dip-process',
    baseMinutes: 0,
    variableMinutesPerCycle: 8.6,
    unitsPerCycle: 1,
    unitName: 'buckets',
    isBatchProcess: false,
  },
  {
    id: 'task-dip-sleeves-boxes',
    groupId: 'dip-processing',
    name: 'Sleeves & Boxes',
    colorVar: '--dip-process',
    baseMinutes: 0,
    variableMinutesPerCycle: 0.86,
    unitsPerCycle: 1,
    unitName: 'cases',
    isBatchProcess: false,
  },
  {
    id: 'task-cheese-mixing',
    groupId: 'dip-mixing',
    name: 'Cheese Mixing',
    colorVar: '--dip',
    baseMinutes: 0,
    variableMinutesPerCycle: 7,
    unitsPerCycle: 1,
    unitName: 'batches',
    isBatchProcess: false,
  },
  {
    id: 'task-cheese-slicing',
    groupId: 'cheese-processing',
    name: 'Cheese Slicing',
    colorVar: '--cheese',
    baseMinutes: 0,
    variableMinutesPerCycle: 10,
    unitsPerCycle: 1,
    unitName: 'pans',
    isBatchProcess: false,
  },
  {
    id: 'task-cheese-dipping',
    groupId: 'cheese-processing',
    name: 'Cheese Dipping',
    colorVar: '--cheese',
    baseMinutes: 0,
    variableMinutesPerCycle: 30,
    unitsPerCycle: 1,
    unitName: 'racks',
    isBatchProcess: false,
  },
  {
    id: 'task-cheese-sealing',
    groupId: 'cheese-processing',
    name: 'Cheese Sealing',
    colorVar: '--cheese',
    baseMinutes: 0,
    variableMinutesPerCycle: 36,
    variableMinutesPerCycleByWorkerCount: {
      2: 18,
    },
    unitsPerCycle: 1,
    unitName: 'racks',
    isBatchProcess: false,
    maxPeopleAffectingDuration: 2,
    assignmentRoles: ['Loading Team', 'Receiving Team'],
  },
  {
    id: 'task-cheese-packing',
    groupId: 'cheese-processing',
    name: 'Cheese Packing',
    colorVar: '--cheese',
    baseMinutes: 0,
    variableMinutesPerCycle: 19.5,
    variableMinutesPerCycleByWorkerCount: {
      2: 9.75,
      3: 6.5,
    },
    unitsPerCycle: 1,
    unitName: 'bins',
    isBatchProcess: false,
    maxPeopleAffectingDuration: 3,
    assignmentRoles: ['Sealer 1', 'Sealer 2', 'Boxer'],
  },
  {
    id: 'task-qa-swab',
    groupId: 'sanitation',
    name: 'QA Swab Inspection',
    colorVar: '--sanitation',
    baseMinutes: 35,
    variableMinutesPerCycle: 0,
    unitsPerCycle: 1,
    unitName: 'inspections',
    isBatchProcess: false,
  },
  {
    id: 'task-dishes',
    groupId: 'sanitation',
    name: 'Dishes & Washdown',
    colorVar: '--sanitation',
    baseMinutes: 65,
    variableMinutesPerCycle: 0,
    unitsPerCycle: 1,
    unitName: 'blocks',
    isBatchProcess: false,
  },
  {
    id: 'task-garbage-recycling',
    groupId: 'sanitation',
    name: 'Garbage & Recycling',
    colorVar: '--sanitation',
    baseMinutes: 25,
    variableMinutesPerCycle: 0,
    unitsPerCycle: 1,
    unitName: 'blocks',
    isBatchProcess: false,
  },
];

export const runTemplates = [
  {
    id: 'run-fermentation',
    name: 'Fermentation Run',
    groupId: 'ferment-prep',
    inputType: 'single',
    inputUnit: 'buckets',
    bucketsPerInputUnit: 1,
    tasks: [
      'task-sanitation',
      'task-stickering',
      'task-boiling',
      'task-mixing',
      'task-cleanup'
    ]
  },
  {
    id: 'run-dip-mixing',
    name: 'Mixing',
    groupId: 'dip-mixing',
    inputType: 'single',
    inputUnit: 'batches',
    bucketsPerInputUnit: 1,
    tasks: [
      'task-cheese-mixing',
      'task-dip-mixing',
    ]
  },
  {
    id: 'run-veg-prep',
    name: 'Veggie Prep Run',
    groupId: 'veg-prep',
    inputType: 'single',
    inputUnit: 'runs',
    bucketsPerInputUnit: 1,
    tasks: [
      'task-veg-beet',
      'task-veg-cilantro',
      'task-veg-jalapeno',
      'task-veg-cucumber',
      'task-veg-smoking-nuts',
      'task-veg-roasting-nuts',
    ]
  },
  {
    id: 'run-packaging-prep',
    name: 'Packaging Prep Run',
    groupId: 'packaging-prep',
    inputType: 'single',
    inputUnit: 'prep sets',
    bucketsPerInputUnit: 1,
    tasks: [
      'task-date-containers',
      'task-sticker-lids',
      'task-tape-boxes',
      'task-dry-mix-prep-set',
    ]
  },
  {
    id: 'run-dip-processing',
    name: 'Dip Filling Run',
    groupId: 'dip-processing',
    inputType: 'single',
    inputUnit: 'buckets',
    bucketsPerInputUnit: 1,
    tasks: [
      'task-dip-filling',
      'task-dip-sealing',
      'task-dip-sleeves-boxes',
    ]
  },
  {
    id: 'run-cheese-processing',
    name: 'Cheese Processing Run',
    groupId: 'cheese-processing',
    inputType: 'single',
    inputUnit: 'racks',
    bucketsPerInputUnit: 1,
    tasks: [
      'task-cheese-slicing',
      'task-cheese-dipping',
      'task-cheese-sealing',
      'task-cheese-packing',
    ]
  },
  {
    id: 'run-sanitation-qa',
    name: 'Sanitation & QA Run',
    groupId: 'sanitation',
    inputType: 'single',
    inputUnit: 'blocks',
    bucketsPerInputUnit: 1,
    tasks: [
      'task-qa-swab',
      'task-dishes',
      'task-garbage-recycling',
    ]
  }
];

export const daysOfWeek = [
  { id: 'mon', name: 'Monday' },
  { id: 'tue', name: 'Tuesday' },
  { id: 'wed', name: 'Wednesday' },
  { id: 'thu', name: 'Thursday' },
  { id: 'fri', name: 'Friday' }
];

// Hours from 7 AM to 5 PM
export const hoursOfDay = Array.from({ length: 11 }, (_, i) => i + 7);
